config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), 
    path('',include('crud.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Home, MyPost, DetailPost,create_protocol,create_process ,UpdatePost, DeletePost

app_name='crud'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('mypost/', MyPost.as_view(), name='mypost'),
    path('detail/<int:pk>', DetailPost.as_view(), name='detail'),
    path('detail/<int:pk>/update', UpdatePost.as_view(), name='update'),
    path('detail/<int:pk>/delete', DeletePost.as_view(), name='delete'),
    path('create/', create_protocol, name='create'),  
    path('create/<int:pk>', create_process, name='create2'),  
]

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
   <meta charset="UTF-8">
   <link href="{% static 'css/header.css'%}" rel="stylesheet">
   <script src="{% static 'js/jquery-3.6.0.min.js'%}" type="text/javascript"></script> 
   {% block extrahead%}
   {% endblock extrahead%}
</head>

<header>
    <h1>Lab</h1>
    <nav class="nav">
        <ul class="head-list">
            <li class="head-list-item"><a href="{% url 'crud:home' %}">HOME</a></li>
            <li class="head-list-item"><a href="{% url 'crud:mypost' %}">MyPOST</a></li>
            <li class="head-list-item"><a href="{% url 'crud:create' %}">New</a></li>
        </ul>
    </nav>
</header>

<body>
{% block content%}
{% endblock content%}
</body>
</html>

templates/create.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead%}
<link href="{% static 'css/create.css'%}" rel="stylesheet">
{% endblock extrahead%}

{% block content %}
<h1 >新しいプロトコール</h1>
<form action="" method="POST">
    {{ formset_protocol.management_form }}
    {% for form in formset_protocol %}
    <div class="field">
        <label for="{{ form.title.id_for_label }}">プロトコール名</label>
        {{form.title}}
    </div>
    <div class="field">
        <label for="{{ form.abst.id_for_label }}"></label>
        {{form.abst}}
    </div>
    <div class="field">
        {{form.id}}
    </div>
    {% endfor %}
    {{error_message}}
    <div class="submit">
        <button type="submit">次へ</button>
    </div>

    {% csrf_token %}
</form>
{% endblock content %}

templates/create2.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead%}
<link href="{% static 'css/create.css'%}" rel="stylesheet">
<script src="{% static 'js/create2.js'%}" type="text/javascript"></script>
{% endblock extrahead%}

{% block content %}
<h1 >手技の追加</h1>
<form action="" method="POST">
    {{ formset_process.management_form }}

    {% for form in formset_process %}
    <div class="button">
        <button type="button" class="add-top-main">main</button>
        <button type="button" class="add-top-sub">sub</button>
    </div>
    <div class="form-block main" id="block-0">
        <div class="field title">
            <label for="{{ form.title.id_for_label }}">プロセス</label>
            {{form.title}}
        </div>
        <div class="field content">
            <label for="{{ form.content.id_for_label }}"></label>
            {{form.content}}
        </div>
        <div class="field time">
            <label for="{{ form.time.id_for_label }}"></label>
            {{form.time}}
        </div>
        <div class="field sub">
            {{form.sub}}
        </div>
        <div class="field rank">
            {{form.rank}}
        </div>
        <div class="field id">
            {{form.id}}
        </div>
        <button type="button" class="remove">削除</button>
    </div>
    <div class="button">
        <button type="button" class="add-main">main</button>
        <button type="button" class="add-sub">sub</button>
    </div>

    {% endfor %}
    {{error_message}}

    <div class="submit">
        <button type="submit">送信</button>
    </div>

    {% csrf_token %}
</form>
{% endblock content %}

templates/delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="post">{% csrf_token %}
   <p>本当に削除してもよろしいですか?</p>
   <input type="submit" value="削除する">
</form>
{% endblock content %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead%}
<link href="{% static 'css/detail.css'%}" rel="stylesheet">
{% endblock extrahead%}

{% block content %}
<div class="container">
    <div class="block title">
        <h2>{{object.title}}</h2>
        <p>作成日：{{ object.created_at }}  作成者：{{object.user}}</p>
        <p class="abst">{{object.abst}}</p>
       {% if object.user == request.user %}  
       <!-- リクエストユーザーと投稿者が等しい場合のみリンク表示 -->
       <a href="{% url 'crud:update' object.pk %}" class="btn btn-primary ms-3" tabindex="-1" role="button" aria-disabled="true">編集</a>
       <a href="{% url 'crud:delete' object.pk %}" class="btn btn-danger ms-3" tabindex="-1" role="button" aria-disabled="true">削除</a>
       {% endif %}
    </div>

    {% for pro in process%}
        {% if pro.sub == False %}
    <div class="block main">
        <h4>{{pro.title}}</h4>
        {% if pro.time != None %}
        <p>所要時間  {{pro.time}}</p>
        {% endif %}
        <p>{{pro.content}}</p>
    </div>
        {% else %}
    <div class="block sub">
        <h4>{{pro.title}}</h4>
        {% if pro.time != None %}
        <p>所要時間  {{pro.time}}</p>
        {% endif %}
        <p>{{pro.content}}</p>
    </div>
        {% endif %}
    {% endfor%}


</div>
{% endblock content %}

templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead%}
<link href="{% static 'css/list.css'%}" rel="stylesheet">
{% endblock extrahead%}

{% block content %}
<div class="container">
    {% if place == "mypost" %}
     <h1> マイ　プロトコール</h1>
    {% endif %}
    {% for item in object_list %}
    <div class="block">
        <h2><a href="{% url 'crud:detail' item.pk %}">{{item.title}}</a></h2>
        <p>作成日: {{ item.created_at }}</p>
        {% if place != "mypost" %}
            <p>投稿者：{{item.user.username}}</p>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="post">{% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="編集">
</form>

{% endblock content %}